{{- if .Values.nodeexporter.deploy }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-node-exporter
  labels:  
    app: {{ template "prometheus-operator.name" . }}-node-exporter
{{ include "prometheus-operator.labels" . | indent 4 }}
spec:
  jobLabel: {{ .Values.nodeexporter.jobLabel }}
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: 30s
{{- end }} 