{{- if and .Values.rbac.create .Values.rbac.pspEnable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "alertmanager.labels.standard" . | indent 4 }}
  name: psp-{{ template "alertmanager.fullname" . }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "alertmanager.fullname" . }}
{{- end }}
