apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alertmanager.fullname" . }} 
data:
  alertmanager.yaml: {{ toYaml .Values.alertmanager.config | b64enc | quote }}
{{- range $key, $val := .Values.alertmanager.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
