apiVersion: v1
kind: Service
metadata:
{{- if .Values.alertmanager.service.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.service.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "alertmanager.labels.standard" . | indent 4 }}
  name: {{ template "alertmanager.fullname" . }}
spec:
  ports:
    - name: http
    {{- if eq .Values.alertmanager.service.type "NodePort" }}
      nodePort: {{ .Values.alertmanager.service.nodePort }}
    {{- end }}
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
{{ include "alertmanager.labels.standard" . | indent 4 }}
  type: "{{ .Values.alertmanager.service.type }}"
{{- with .Values.alertmanager.service.extraSpecs }}
{{ toYaml . | indent 4 }}
{{- end }}
