{{- if .Values.alertmanager.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ toYaml .Values.alertmanager.labels | indent 4 }}
  name: alertmanager
spec:
  jobLabel: {{ .Values.alertmanager.serviceMonitor.jobLabel }}
  selector:
{{ toYaml .Values.alertmanager.service.selector | indent 4 }}
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: web
    interval: 30s
{{- end }}
