{{- if and .Values.grafana.deploy .Values.grafana.prometheusOperatorServiceName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.prometheusOperatorServiceName }}
  labels:  
    app: {{ template "prometheus-operator.name" . }}-grafana
{{ include "prometheus-operator.labels" . | indent 4 }}
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: {{ template "prometheus-operator.fullname" . }}-prometheus
{{- end }}