{{- if .Values.kubeStateMetrics.deploy }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-state-metrics
  labels:  
    app: {{ template "prometheus-operator.name" . }}-kube-state-metrics
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  jobLabel: app
  endpoints:
  - interval: 30s
    port: http
    honorLabels: true
  selector:
    matchLabels:
      app: kube-state-metrics
      release: "{{ .Release.Name }}"
{{- end }}