{{- if .Values.kubeStateMetrics.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
spec:
  endpoints:
  - interval: 30s
    port: http
    honorLabels: true
  jobLabel: {{ .Values.kubeStateMetrics.serviceMonitor.jobLabel }}
  selector:
{{ toYaml .Values.kubeStateMetrics.serviceMonitor.selector | indent 4 }}
{{- end }}