{{- if .Values.kubeDns.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:    
{{ toYaml .Values.kubeDns.labels | indent 4}}
{{ include "prometheus-operator.labels.global" . | indent 4 }} 
  name: kube-dns
spec:
  jobLabel: {{ .Values.kubeDns.serviceMonitor.jobLabel }}
  selector:
{{ toYaml .Values.kubeDns.service.selector | indent 4 }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics-dnsmasq
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  - port: http-metrics-skydns
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- end }}