{{- if .Values.kubeDns.selfServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:    
    {{ .Values.kubeDns.labels | indent 4}}
  name: {{ template "prometheus-operator.fullname" . }}
spec:
  jobLabel: {{ .Values.kubeDns.jobLabel }}
  selector:
    matchLabels:
      {{ .Values.kubeDns.service.selector | indent 6 }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics-dnsmasq
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  - port: http-metrics-skydns
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- end -}}