dependencies:

  - name: kube-state-metrics
    version: 0.8.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubeStateMetrics.deploy

  - name: prometheus-node-exporter
    version: 0.5.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nodeexporter.deploy

  - name: grafana
    version: 1.17.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.deploy
