{{- if and .Values.global.rbac.create .Values.global.rbac.pspEnable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

