{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s-config
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus.fullname" . }}-config
subjects:
- kind: ServiceAccount
    name: {{ template "prometheus-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
