{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: {{ template "prometheus.fullname" . }}-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus.serviceAccountName" . }} 
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.serviceAccountName" . }} 
    namespace: {{ .Release.Namespace }}
{{- end }}