{{- if .Values.prometheus.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:    
{{ toYaml .Values.prometheus.labels | indent 4 }}
  name: prometheus
spec:
  selector:
{{ toYaml .Values.prometheus.serviceMonitor.selector | indent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: web
    interval: 30s
{{- end }}
