apiVersion: v1
kind: Service
metadata:
{{- with .Values.prometheus.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "prometheus.labels.standard" . | indent 4 }}
    prometheus: k8s
  name: prometheus-k8s
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    {{ .Values.prometheus.service.selector | indent 4 }}
{{- with .Values.prometheus.service.extraSpecs }}
{{ toYaml . | indent 4 }}
{{- end }}
