{{- if and .Values.global.rbac.create .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
imagePullSecrets: 
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
