{{- if .Values.rbacEnable }}
{{- if .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: 
{{ include "prometheus-operator.labels.standard" . | indent 4 }}
  name: {{ template "prometheus-operator.serviceAccountName" . }}
imagePullSecrets: 
{{ toYaml .Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end -}}
{{- end -}}
