{{- if .Values.kubeControllerManager.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-controller-manager
  labels:  
    app: {{ template "prometheus-operator.name" . }}-kube-controller-manager
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    jobLabel: kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeControllerManager.service.port }}
      protocol: TCP
  selector:
{{ include "prometheus-operator.rangeskipempty" .Values.kubeControllerManager.service.selector | indent 4 }}
  type: ClusterIP
{{- end }}