{{- if .Values.kubeScheduler.deploy }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-scheduler
  labels:  
    app: {{ template "prometheus-operator.name" . }}-kube-scheduler
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: {{ template "prometheus-operator.name" . }}-kube-scheduler
      release: {{ .Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
{{- end }}