{{- if .Values.kubeScheduler.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-scheduler
  labels:
    app: {{ template "prometheus-operator.name" . }}-kube-scheduler
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    jobLabel: kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeScheduler.service.port}}
      protocol: TCP
      targetPort: {{ .Values.kubeScheduler.service.targetPort}}
  selector:
  {{ include "prometheus-operator.rangeskipempty" .Values.kubeScheduler.service.selector | indent 4 }}
  type: ClusterIP
{{- end -}}