apiVersion: v1
description: The ElasticSearch operator is designed to manage one or more elastic search clusters. Included in the project (initially) is the ability to create the Elastic cluster, deploy the data nodes across zones in your Kubernetes cluster, and snapshot indexes to AWS S3.
engine: gotpl
maintainers:
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
name: elasticsearch-operator
sources:
  - https://github.com/coreos/elasticsearch-operator
version: 0.0.6
