apiVersion: v1
description: Provides easy monitoring definitions for Kubernetes services, and deployment and management of Prometheus instances.
engine: gotpl
maintainers:
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
name: elasticsearch-operator
sources:
  - https://github.com/coreos/elasticsearch-operator
version: 0.0.6
