{{- if .Values.coreDns.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ toYaml .Values.coreDns.serviceMonitor.labels | indent 4}}
  name: coredns
spec:
  jobLabel: {{ .Values.coreDns.serviceMonitor.jobLabel }}
  selector:
{{ toYaml .Values.coreDns.serviceMonitor.selector | indent 6 }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
 
{{- end }}
