{{- if .Values.nodeExporter.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ toYaml .Values.nodeExporter.labels | indent 4 }}
{{ include "prometheus-operator.labels.standard" . | indent 4 }}
  name: node-exporter
spec:
  jobLabel: {{ .Values.nodeExporter.serviceMonitor.jobLabel }}
  selector:
{{ toYaml .Values.nodeExporter.service.selector | indent 4 }}
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: metrics
    interval: 30s
{{- end }}    