{{- if .Values.kubeControllerManager.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-controller-manager.fullname" . }}
  labels:
{{ toYaml .Values.kubeControllerManager.labels | indent 4 }}
spec:
  jobLabel: {{ .Values.kubeControllerManager.serviceMonitor.jobLabel }}
  selector:
 {{ toYaml .Values.kubeControllerManager.serviceMonitor.selector | indent 4 }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- end }}