{{- if .Values.coreDns.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-coredns
  labels:  
    app: {{ template "prometheus-operator.name" . }}-coredns
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    jobLabel: coredns
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.coreDns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.coreDns.service.port }}
  selector:
{{ include "prometheus-operator.rangeskipempty" .Values.coreDns.service.selector | indent 4 }}
{{- end }}