{{- if .Values.coreDns.serviceMonitor.selfMonitor }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ toYaml .Values.coreDns.labels | indent 4 }}
  name: {{ template "core-dns.fullname" . }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.coreDns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.coreDns.service.port }}
  selector:
{{ include "prometheus-operator.rangeskipempty" .Values.coreDns.service.selector | indent 4 }}
{{- end }}