{{- if .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ toYaml .Values.prometheus.labels | indent 4 }}
  name: {{ template "prometheus.fullname" . }}-additional-alertmanager-configs
data:
  additional-alertmanager-configs.yaml: {{ toYaml .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs | b64enc | quote }}
{{- end }}