{{- if .Values.prometheus.prometheusSpec.additionalScrapeConfigs }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ toYaml .Values.prometheus.labels | indent 4 }}
  name: {{ template "prometheus.fullname" . }}-additional-scrape-configs
data:
  additional-scrape-configs.yaml: {{ toYaml .Values.prometheus.prometheusSpec.additionalScrapeConfigs | b64enc | quote }}
{{- end }}