{{- if and .Values.prometheus.deploy .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-prometheus-config
  labels:  
    app: {{ template "prometheus-operator.name" . }}-prometheus
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
{{- end}}