{{- if  .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "prometheus.fullname" . }}-config
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
{{- end}}