{{- if and .Values.prometheus.deploy .Values.prometheus.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-prometheus
  labels:  
    app: {{ template "prometheus-operator.name" . }}-prometheus
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:  
  selector:
    matchLabels:
      app: {{ template "prometheus-operator.name" . }}-prometheus
      release: {{ .Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: web
    interval: 30s
{{- end }}
