apiVersion: v1
kind: Service
metadata:
  labels:
{{ toYaml .Values.prometheus.labels | indent 4 }}
  name: {{ include "prometheus.fullname" . }}
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
{{ include "prometheus-operator.rangeskipempty" .Values.prometheus.service.selector | indent 4 }}

