{{- if not .Values.aws.role }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudwatch-exporter.fullname" . }}
  labels:
    app: {{ template "cloudwatch-exporter.name" . }}
    chart: {{ template "cloudwatch-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end }}
