{{- if .Values.prometheusOperator.deploy }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-operator
  labels:  
    app: {{ template "prometheus-operator.name" . }}-operator
{{ include "prometheus-operator.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "prometheus-operator.name" . }}-operator
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels: 
        app: {{ template "prometheus-operator.name" . }}-operator
{{ include "prometheus-operator.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ template "prometheus-operator.name" . }}
          image: "{{ .Values.prometheusOperator.image.repository }}:{{ .Values.prometheusOperator.image.tag }}"
          imagePullPolicy: "{{ .Values.prometheusOperator.image.pullPolicy }}"
          args:
          {{- if .Values.prometheusOperator.kubeletService.enabled }}
            - --kubelet-service={{ .Values.prometheusOperator.kubeletService.namespace }}/{{ .Values.prometheusOperator.kubeletService.name }}
          {{- end }}
            - --logtostderr=true
            - --localhost=127.0.0.1
            - --prometheus-config-reloader={{ .Values.prometheusOperator.prometheusConfigReloader.repository }}:{{ .Values.prometheusOperator.prometheusConfigReloader.tag }}
            - --config-reloader-image={{ .Values.prometheusOperator.configmapReload.repository }}:{{ .Values.prometheusOperator.configmapReload.tag }}
          ports:
            - containerPort: 8080
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534          
    {{- if .Values.global.rbac.create }}
      serviceAccountName: {{ template "prometheus-operator.operator.serviceAccountName" . }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}