{{- if .Values.prometheusOperator.deploy }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-operator
  labels:  
    app: {{ template "prometheus-operator.name" . }}-operator
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "prometheus-operator.name" . }}-operator
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels: 
        app: {{ template "prometheus-operator.name" . }}-operator
        chart: {{ template "prometheus-operator.chartref" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
        - name: {{ template "prometheus-operator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
          {{- if .Values.kubelet.enabled }}
            - --kubelet-service={{ .Values.kubelet.namespace }}/{{ .Values.kubelet.name }}
          {{- end }}
            - --logtostderr=true
            - --localhost=127.0.0.1
            - --prometheus-config-reloader={{ .Values.prometheusConfigReloader.repository }}:{{ .Values.prometheusConfigReloader.tag }}
            - --config-reloader-image={{ .Values.configmapReload.repository }}:{{ .Values.configmapReload.tag }}
          ports:
            - containerPort: 8080
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534          
    {{- if and .Values.serviceAccount }}
      serviceAccountName: {{ template "prometheus-operator.fullname" . }}-operator
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}