{{- if and .Values.prometheusOperator.deploy .Values.global.rbac.create .Values.global.rbac.pspEnable }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-operator-psp
  labels:  
    app: {{ template "prometheus-operator.name" . }}-operator
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-operator.fullname" . }}-operator-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.fullname" . }}-operator
    namespace: {{ .Release.Namespace }}
{{- end }}
