{{- if and .Values.prometheusOperator.deploy .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-operator
  labels:  
    app: {{ template "prometheus-operator.name" . }}-operator
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
imagePullSecrets: 
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
