{{- if .Values.prometheusOperator.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-operator
  labels:  
    app: {{ template "prometheus-operator.name" . }}-operator
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: {{ template "prometheus-operator.name" . }}-operator
    release: {{ .Release.Name | quote }}

{{- end }}