{{- if and .Values.prometheus.deploy .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-prometheus-am-confg
  labels:  
    app: {{ template "prometheus-operator.name" . }}-prometheus-am-confg
{{ include "prometheus-operator.labels" . | indent 4 }}
data:
  additional-alertmanager-configs.yaml: {{ toYaml .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs | b64enc | quote }}
{{- end }}