apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-postgres-exporter.name" . }}
    chart: {{ template "prometheus-postgres-exporter.chart" . }}    
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"