{{- if .Values.alertmanager.ingress.enabled }}
{{- $routePrefix := .Values.routePrefix }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.alertmanager.ingress.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{ toYaml .Values.alertmanager.labels | indent 4 }}
  name: {{ template "alertmanager.fullname" . }}
spec:
  rules:
    {{- range $host := .Values.alertmanager.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: "{{ $routePrefix }}"
            backend:
              serviceName: alertmanager-main
              servicePort: 9093
    {{- end }}
{{- if .Values.alertmanager.ingress.tls }}
  tls:
{{ toYaml .Values.alertmanager.ingress.tls | indent 4 }}
{{- end }}
{{- end }}