{{- if and .Values.alertmanager.deploy .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-alertmanager
  labels:  
    app: {{ template "prometheus-operator.name" . }}-alertmanager
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-operator.fullname" . }}-alertmanager
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.fullname" . }}-alertmanager
    namespace: {{ .Release.Namespace }}
{{- end }}
