{{- if and .Values.alertmanager.deploy .Values.global.rbac.create .Values.alertmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-alertmanager
  labels:  
    app: {{ template "prometheus-operator.name" . }}-alertmanager
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
imagePullSecrets: 
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
