apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
{{ toYaml .Values.alertmanager.labels | indent 4 }}
spec:
  ports:
    - name: web
    {{- if eq .Values.alertmanager.service.type "NodePort" }}
      nodePort: {{ .Values.alertmanager.service.nodePort }}
    {{- end }}
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
{{ toYaml .Values.alertmanager.service.selector | indent 4 }}
  type: "{{ .Values.alertmanager.service.type }}"
