{{- if .Values.alertmanager.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-alertmanager
  labels:  
    app: {{ template "prometheus-operator.name" . }}-alertmanager
    chart: {{ template "prometheus-operator.chartref" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - name: web
    {{- if eq .Values.alertmanager.service.type "NodePort" }}
      nodePort: {{ .Values.alertmanager.service.nodePort }}
    {{- end }}
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: alertmanager
    alertmanager: {{ template "prometheus-operator.fullname" . }}-alertmanager
  type: "{{ .Values.alertmanager.service.type }}"
{{- end }}